### ISSUE TITLE
How can I run this app via Andriod Studio

### ISSUE THREAD

**Issue by LU-House** [jkangzhang/garbage-sorting-assistant#1]
Hello Mr.Zhang, 
I'm a high school student. I‘m very interested in your app. I want to run it via Andriod Studio. However, I don't where to start it. Thus, could you make a demostration for me? I appreciate it.

**Comment by jkangzhang** [comment]
Hello Lu,

I am glad that you like this project. But I am sorry to say that as you can see in the [README](https://github.com/jkangzhang/garbage-sorting-assistant/blob/master/README.md), this project is only a proposal which means I did not do implementation yet.

**Comment by LU-House** [comment]
Hello Mr.Zhang,
Thanks for your reply and sorry for my late reply. I can fully understand
that. I think I will change other topic about environmental science.
Anyway, Thank you!

Best regards,

Zeyu Lu










franksayszhang <notifications@github.com> 于2020年8月28日周五 上午11:50写道：
